# Generic production config.
# Copied to config.yml if needed by lute.main

ENV: prod
DBNAME: lute.db
#ENV: dev
#DBNAME: teslute.db
#DATAPATH: /home/fan/.local/share/test_lute
# DATAPATH is not set: user data should be
# stored in PlatformDirs.user_data_dir
# (ref https://pypi.org/project/platformdirs/).

# BACKUP_PATH is not set, user should choose.
